import React from 'react';
import PropTypes from 'prop-types';
import {
  AliwangwangOutlined,
  AndroidOutlined,
  ApiOutlined,
  AppleOutlined,
  AppstoreAddOutlined,
  AppstoreOutlined,
  BarsOutlined,
  CalendarOutlined,
  CameraOutlined,
  CloseCircleOutlined,
  CloseOutlined,
  CheckCircleOutlined,
  CheckOutlined,
  ClockCircleOutlined,
  CloudOutlined,
  CodeOutlined,
  CoffeeOutlined,
  CopyOutlined,
  CustomerServiceOutlined,
  DashOutlined,
  DatabaseOutlined,
  DeleteOutlined,
  DesktopOutlined,
  DownOutlined,
  EditOutlined,
  EnvironmentOutlined,
  ExclamationCircleOutlined,
  EyeOutlined,
  FileOutlined,
  FileTextOutlined,
  FileUnknownOutlined,
  FolderAddOutlined,
  FolderOpenOutlined,
  FolderOutlined,
  ForkOutlined,
  FrownOutlined,
  GithubOutlined,
  GlobalOutlined,
  HddOutlined,
  IdcardOutlined,
  ImportOutlined,
  InboxOutlined,
  InfoCircleOutlined,
  KeyOutlined,
  LineChartOutlined,
  LockOutlined,
  LogoutOutlined,
  MailOutlined,
  MedicineBoxOutlined,
  MehOutlined,
  MobileOutlined,
  MinusCircleOutlined,
  MinusOutlined,
  NotificationOutlined,
  PayCircleOutlined,
  PictureOutlined,
  PlayCircleOutlined,
  PlusCircleOutlined,
  PlusOutlined,
  PoweroffOutlined,
  QuestionCircleOutlined,
  ReloadOutlined,
  RocketOutlined,
  SafetyOutlined,
  SaveOutlined,
  SearchOutlined,
  SettingOutlined,
  ShareAltOutlined,
  ShoppingCartOutlined,
  SolutionOutlined,
  StarFilled,
  StarOutlined,
  SwapOutlined,
  TagOutlined,
  TeamOutlined,
  FormOutlined,
  SnippetsOutlined,
  ToolOutlined,
  UnlockOutlined,
  UpOutlined,
  UserOutlined,
  VideoCameraOutlined,
  WarningOutlined,
  WifiOutlined
} from '@ant-design/icons';

// Map legacy icon names to Ant Design v6 components so old string-based usages no longer rely on compat.
const ICON_MAP = {
  'aliwangwang-o': AliwangwangOutlined,
  android: AndroidOutlined,
  'android-o': AndroidOutlined,
  api: ApiOutlined,
  apple: AppleOutlined,
  'apple-o': AppleOutlined,
  appstore: AppstoreOutlined,
  'appstore-add': AppstoreAddOutlined,
  'appstore-o': AppstoreOutlined,
  bars: BarsOutlined,
  calendar: CalendarOutlined,
  camera: CameraOutlined,
  'camera-o': CameraOutlined,
  card: IdcardOutlined,
  case: SnippetsOutlined,
  'check-circle': CheckCircleOutlined,
  check: CheckOutlined,
  'clock-circle-o': ClockCircleOutlined,
  close: CloseOutlined,
  'close-circle': CloseCircleOutlined,
  coffee: CoffeeOutlined,
  copy: CopyOutlined,
  'code-o': CodeOutlined,
  'cloud-o': CloudOutlined,
  'customer-service': CustomerServiceOutlined,
  danger: CloseCircleOutlined,
  database: DatabaseOutlined,
  delete: DeleteOutlined,
  desktop: DesktopOutlined,
  dashed: DashOutlined,
  down: DownOutlined,
  edit: EditOutlined,
  'environment-o': EnvironmentOutlined,
  'exclamation-circle': ExclamationCircleOutlined,
  'exclamation-circle-o': ExclamationCircleOutlined,
  'eye-o': EyeOutlined,
  file: FileOutlined,
  'file-text': FileTextOutlined,
  flex: AppstoreOutlined,
  folder: FolderOutlined,
  'folder-add': FolderAddOutlined,
  'folder-open': FolderOpenOutlined,
  fork: ForkOutlined,
  'frown-o': FrownOutlined,
  github: GithubOutlined,
  global: GlobalOutlined,
  hdd: HddOutlined,
  idcard: IdcardOutlined,
  import: ImportOutlined,
  inbox: InboxOutlined,
  info: InfoCircleOutlined,
  'info-circle': InfoCircleOutlined,
  inter: ApiOutlined,
  key: KeyOutlined,
  'line-chart': LineChartOutlined,
  lock: LockOutlined,
  logout: LogoutOutlined,
  mail: MailOutlined,
  matrix: AppstoreOutlined,
  'medicine-box': MedicineBoxOutlined,
  'meh-o': MehOutlined,
  mobile: MobileOutlined,
  module: AppstoreAddOutlined,
  monotone: AppstoreOutlined,
  'no-change': MinusOutlined,
  nochange: MinusOutlined,
  'no-data': FileUnknownOutlined,
  nodata: FileUnknownOutlined,
  nofollow: FileUnknownOutlined,
  nomemberingroup: TeamOutlined,
  nomemberinproject: TeamOutlined,
  noproject: AppstoreOutlined,
  notification: NotificationOutlined,
  password: KeyOutlined,
  picture: PictureOutlined,
  'play-circle-o': PlayCircleOutlined,
  plus: PlusOutlined,
  'plus-circle': PlusCircleOutlined,
  poweroff: PoweroffOutlined,
  primary: CheckCircleOutlined,
  question: QuestionCircleOutlined,
  'question-circle': QuestionCircleOutlined,
  'question-circle-o': QuestionCircleOutlined,
  reload: ReloadOutlined,
  rocket: RocketOutlined,
  safety: SafetyOutlined,
  save: SaveOutlined,
  search: SearchOutlined,
  setting: SettingOutlined,
  'share-alt': ShareAltOutlined,
  'shopping-cart': ShoppingCartOutlined,
  solution: SolutionOutlined,
  star: StarFilled,
  'star-o': StarOutlined,
  swap: SwapOutlined,
  'tag-o': TagOutlined,
  team: TeamOutlined,
  textarea: FormOutlined,
  tool: ToolOutlined,
  unlock: UnlockOutlined,
  up: UpOutlined,
  user: UserOutlined,
  warning: WarningOutlined,
  wifi: WifiOutlined,
  'pay-circle-o': PayCircleOutlined,
  'minus-circle-o': MinusCircleOutlined
};

const normalizeName = value => (value || '').trim().toLowerCase();

const pickIcon = name => {
  const key = normalizeName(name);
  const fallbackKey = key.endsWith('-o') ? key.slice(0, -2) : '';
  return ICON_MAP[key] || ICON_MAP[fallbackKey] || QuestionCircleOutlined;
};

const Icon = ({ name, type, ...rest }) => {
  const iconName = name || type;
  if (!name && type && process.env.NODE_ENV !== 'production') {
    // Surface legacy usage early so v1-5 style imports don't slip back in.
    console.error('Icon no longer supports the legacy `type` prop. Use `name` instead.');
  }
  const Component = pickIcon(iconName);
  return <Component {...rest} />;
};

Icon.propTypes = {
  name: PropTypes.string,
  type: PropTypes.string
};

export default Icon;
